import type { Metadata } from 'next';
import { Inter, Dancing_Script } from 'next/font/google';
import './globals.css';

import TopNav from './components/TopNav';
import BottomFooter from './components/BottomFooter';

const inter = Inter({ subsets: ['latin'] });

const petsFonts = Dancing_Script({
  weight: ['400', '500', '600', '700',],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Pets em Pontos',
  description: 'Generated by P61st',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <nav className={petsFonts.className}>
          <TopNav />
        </nav>

        <main>
          {children}          
        </main>

        <footer className={petsFonts.className}>
          <BottomFooter />
        </footer>

      </body>
    </html>
  )
}
